### ISSUE TITLE
Portail repos

### ISSUE THREAD

**Issue by JJeanniard** [kyweez/CDA-RESSOURCES#1]
Création d'un dossier de docs et utilisation de https://jekyllrb.com/ pour une visualisation du repo plus conviviale.  
Travail sur la branche "feature/jjeanniard_docs".

**Comment by JJeanniard** [comment]
Un choix sur le style du portail du repos est à faire sur les liens suivant dans le chapitre [jekyll](https://jekyllrb.com/docs/themes/#pick-up-a-theme), de preference gratuit.

**Comment by JJeanniard** [comment]
@kyweez il me faudrait me faire la procédure dans le lien ci-joint -> [Docs GitHub](https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site), sur la branche gh-pages.
Thank you

**Comment by JJeanniard** [comment]
@kyweez, il me faudrait protéger la branche "gh-pages", à la suite de la mise en place de la page.

**Comment by kyweez** [comment]
@JJeanniard Done.

**Comment by kyweez** [comment]
Allez hop c'est fini !
