### ISSUE TITLE
Gestion de projet

### ISSUE THREAD

**Issue by JJeanniard** [kyweez/CDA-RESSOURCES#2]
Faire un update du document pour ajouter un chapitre de système de restriction sur les branches lors de la gestion du projet sur Github.  
Travail sur la branche hotfix/jjeanniard.

**Comment by JJeanniard** [comment]
Si étape sur la restrictions, il faudrait une étape sur le review accepte, à retravailler, refuser et les conséquences

**Comment by kyweez** [comment]
Ok je m'en charge

**Comment by JJeanniard** [comment]
hi, il manque un chapitre

**Comment by kyweez** [comment]
😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭

**Comment by JJeanniard** [comment]
suite ticket #94
