### ISSUE TITLE
Update Web Site

### ISSUE THREAD

**Issue by JJeanniard** [kyweez/CDA-RESSOURCES#46]
Mettre à jour la partir "[RESSOURCES-FICHIER -> FICHIER](https://kyweez.github.io/CDA-RESSOURCES/ressources_externes/fichier)" :
- [x] pour afficher une liste des fichiers qui se trouve dans le dossier // pas retenue
ou 
- [x] changer les réglés dans le markdown en disent de mettre le lien du fichier suivie des réglés déjà définis.

Et :
- [x] automatiser les mises à jour de master à gh-pages

**Comment by kyweez** [comment]
On se fait un call pour ça demain, pour que tu m'explique en détails ? 😄

**Comment by JJeanniard** [comment]
j'ai pas regarder, si on pouvais listé un dossier ou fichier automatiquement en markdown
