### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by JJeanniard** [kyweez/CDA-RESSOURCES#47]
Procédure sur comment mettre à jour automatiquement :
- [x] d'un "repertoire forked" depuis "le repertoire propriétaire", 
- [ ] d'une branche à une autre ......
- [ ] ticket #38 est en lien avec ceci

**Comment by JJeanniard** [comment]
Attente de relecture pour la premiere partir de la documentation @kyweez

**Comment by kyweez** [comment]
Je suis en maraude, je fais ça à mon retour 😉

**Comment by JJeanniard** [comment]
Suite sur le ticket #94
